### ISSUE TITLE
tournament setup

### ISSUE THREAD

**Issue by tiberakis** [phpchess/phpchess#12]
I need to setup a tournament and I want that all the games can't start before the decided (by the admin) time. It is a tournament among schools, and we want to make all the games to start at the same time. Is there any way to do that? 

I have a second question. Does the software manage tournaments deciding who is playing in the rounds after the first one?

Thank you much.

**Comment by phpchess** [comment]
Hello,

Thank you for your interest in phpchess. This is a good question, and one that shows probably the weakest side of phpchess. Tournaments are in essence manually managed (the way they are coded in php is basically as a record for admins, who can create specific games for players). You can create tournaments, and select match ups, but there is literally zero automation. Apologies for our lack of development in that area. 

Once you create a game within a tournament it appears as a game in the players front page (the game has a little tournament trophy picture on it). But managing progress and so on is not automatic, nor are Start times. 

The only way I can see you do this is to sit down at the time and create the games. I am really sorry.

Kind regards

Christian

**Comment by tiberakis** [comment]
Ok, thank you anyway for your prompt reply. I will do what you are
suggesting.

Kind regards

Marco

2016-12-22 11:55 GMT+01:00 Christian Blumhoff <notifications@github.com>:

> Hello,
>
> Thank you for your interest in phpchess. This is a good question, and one
> that shows probably the weakest side of phpchess. Tournaments are in
> essence manually managed (the way they are coded in php is basically as a
> record for admins, who can create specific games for players). You can
> create tournaments, and select match ups, but there is literally zero
> automation. Apologies for our lack of development in that area.
>
> Once you create a game within a tournament it appears as a game in the
> players front page (the game has a little tournament trophy picture on it).
> But managing progress and so on is not automatic, nor are Start times.
>
> The only way I can see you do this is to sit down at the time and create
> the games. I am really sorry.
>
> Kind regards
>
> Christian
>
