### ISSUE TITLE
phpchess not installing on a php7 server

### ISSUE THREAD

**Issue by mrsilver512** [phpchess/phpchess#13]
I have recently encountered an issue when I am trying to install phpchess on a php7 server (Specifically on a Laravel Homestead Virtual Machine). My server has been giving errors on deprecated functions such as mysql_connect().

**Comment by phpchess** [comment]
Hi,

We are not centrally expecting to update phpchess for version 7. The project is on GitHub so feel free to update.

Christian

**Comment by mrsilver512** [comment]
Alright. Many thanks.
