### ISSUE TITLE
Adding a new game

### ISSUE THREAD

**Issue by tiberakis** [phpchess/phpchess#14]
Hello,
when i try to add a new game, among two different players, I receive the message:
"Same person cannot play both sides".

Any suggestion? Thank you.

**Comment by phpchess** [comment]
Hi,

Apologies if this is not working right. Can you give a bit more background? 
How many players are there? Is the behavior consistent for all players? Are all player full members (or are the accepted on the server)? 

I currently can't replicate the error. 

Sorry to be a pain. Would be so much nicer for all if I could just fix it :( 

Sorry.

Christian

**Comment by tiberakis** [comment]
I have 86 players on the server, all full members but six that are
disabled. The behavior is always the same, for any of the players, so that
i can't create games, as admin, for any players. On the contrary I can
create games, without problems, inside a tournament.

thank you

2016-12-29 21:13 GMT+01:00 Christian Blumhoff <notifications@github.com>:

> Hi,
>
> Apologies if this is not working right. Can you give a bit more
> background?
> How many players are there? Is the behavior consistent for all players?
> Are all player full members (or are the accepted on the server)?
>
> I currently can't replicate the error.
>
> Sorry to be a pain. Would be so much nicer for all if I could just fix it
> :(
>
> Sorry.
>
> Christian
>
