### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by chiweb7** [phpchess/phpchess#15]
Hi
I get this error on the instalation when im in the initial settings step

Fatal error: Uncaught Error: Call to undefined function mysql_connect() in /srv/users/serverpilot/apps/ajedrez/public/club/install/install.php:503 Stack trace: #0 /srv/users/serverpilot/apps/ajedrez/public/club/install/install.php(265): update_settings(Array) #1 {main} thrown in /srv/users/serverpilot/apps/ajedrez/public/club/install/install.php on line 503

**Comment by chiweb7** [comment]
Never mind it was because the server is on PHP 7.0 I switch back to php 5.6 and everything is working OK.

**Comment by phpchess** [comment]
Ok :)
Thanks for looking at phpchess. I hope it works for you.

Christian
