### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by chandrumcd** [phpchess/phpchess#16]
Hi team,

I want to develop a website for playing and training a chess. I try your software but i got many errors when i install the software.

Help me to fix the issue.

Thanks and Regards,
Chandra sekar.M

**Comment by phpchess** [comment]
Hi Chandra,

Thank you for trying phpChess. Sorry to hear you are having errors.
If you would like me to help you please provide more information.
1) What set-up do you have (php version, mysql version,...)?
2) When do you get the errors
3) Did you go through the installation? Did that give errors? If so, what
were they?
4) Can you provide a link to the installation?

Kind regards
Christian

**Comment by chandrumcd** [comment]
Hi Christian,

I am using PHP version 5.6.19.
The errors are refer in the screen shot. 
Kindly help me to fix the issue.

Thanks and Regards
Chandra Sekar

![screen1](https://cloud.githubusercontent.com/assets/10278284/24849071/a6752e72-1de7-11e7-8277-5f9eda14ec5d.png)
![screen2](https://cloud.githubusercontent.com/assets/10278284/24849072/a676f252-1de7-11e7-9a77-a3b3320278e7.png)

**Comment by phpchess** [comment]
Hello Chandra,

Thank you for taking a look at phpChess. 

Please note that these are notices and warnings inherent in the php version. Simply edit php.ini from reporting all warnings and notices to only display errors (production setting) and everything will work as designed. Restart Apache and you should no notices and warning left. 

Kind regards

Christian

**Comment by chandrumcd** [comment]
What are all the changes are done in the php.ini????

**Comment by phpchess** [comment]
Hi,

Only one. Please look up errors and warning settings. Please refer to error setting for php: 
http://php.net/manual/en/function.error-reporting.php

In general Production servers should only log errors, and not display warnings or errors.

Kind regards

Christian
