### ISSUE TITLE
3d View is there or not

### ISSUE THREAD

**Issue by jmtittechnologies** [phpchess/phpchess#17]
Hi I want mobile device should be in 3d view board
please check 👍 
http://jtiscione.github.io/chessboard3js/index.html

**Comment by phpchess** [comment]
We checked it out. It looks nice, but after checking with out customer admins we decided against it. All our users prefer the 2D view of a board. Don't get me wrong. your work looks very nice. feel free to offer an integrated version into phpchess. we are happy to link to you.
