### ISSUE TITLE
cant get email to work

### ISSUE THREAD

**Issue by AlphabetoPT** [phpchess/phpchess#6]
Hello.
I cant set my email settings.
I have now deleted the whole folder.
I'll reinstall it if you help me because i lost the whole morning and i can't pass the email settings.

I may give you temporary access to my vps if needed.

Btw, i am using OVH vps. I read somewhere that vps may have restrictions using phpmail settings, however i run a site at it (www.zionportugal.com) and SMTP functions using Gmail servers are working perfectly.
I would love to use this script in my multigaming community but i'll need your help.
We may donate if done quickly.

Thanks

**Comment by phpchess** [comment]
Hi,

we use the phpmailer script.you can find it in phpchess/includes/phpmailer. we are using version 1.73, which is admitedly very old. the phpmailer script is also on github as far as I can work out: https://github.com/PHPMailer/PHPMailer. PHPMailer has a great advantage as it permits you to test the script. have a look in the test folder and try the scripts in there. In the past we have simply replaced the phpmailer folder with the later versions, which you can try, but we have had no need for that. And we can't gurantee that it will work.

However before we look at the script normally the server works well without any settings saved. It picks up the php capabilities from phpmailer as is, which detects the server config. 

I am happy to help. You can mail me directly at chrizb at yahoo dot com

**Comment by AlphabetoPT** [comment]
i read somewhere that you can access my vps and do it for me?
if so.. you da man!
but i feel kinda unsafe doin' that as you can expect.
Can you come to my teamspeak to talk a little?
if so ts.zionportugal.com (ts3)

Thanks
As i can said we can donate a SMALL ammount to your project by paypal since the payday is coming quickly. thanks

**Comment by AlphabetoPT** [comment]
Hello i sent you the mail but i am getting no response from you.
Thanks

**Comment by phpchess** [comment]
Hi,

I am bit sure what happened. Maybe an overactive spam filter. Can you please resend your response to this email? 

Thanks

Christian

**Comment by AlphabetoPT** [comment]
Yes i can
Em 02/09/2015 10:41, "phpchess" <notifications@github.com> escreveu:

> Hi,
>
> I am bit sure what happened. Maybe an overactive spam filter. Can you
> please resend your response to this email?
>
> Thanks
>
> Christian
>

**Comment by phpchess** [comment]
Happy to help. When are you online?

Christian

**Comment by AlphabetoPT** [comment]
Hello again.
Sorry for the delay.
I am ready to do it now.
I'll be online afternoons Greenwich time.

Regards

---
Este e-mail foi verificado em termos de vírus pelo software antivírus Avast.
https://www.avast.com/antivirus
