### ISSUE TITLE
Emails not arriving

### ISSUE THREAD

**Issue by AlphabetoPT** [phpchess/phpchess#7]
Hello sir,
I really NEED this script because i love chess and some of my friends too.
I managed to install script and acess to administrator page however smtp settings on email seems not to be working properly because failed email logs are empty however the emails are not arriving even in spam accounts.

The configs i tried are:

SMTP URL:  
smtp.gmail.com
SMTP Port:  
587 ( i tried with 465 too )
SMTP User:  
my email
SMTP Pass:  
my email pass
Reply To Email: 
my email again ( i tried to use a different)

Note please that i authorized my vps on gmail so it's not a matter of authentication.

Any clues how to solve this problem?
Thank you very much for your hard work doing this.

**Comment by AlphabetoPT** [comment]
NOTE: Due to previous ticket i did empty my email settings as you stated, i have phpmailer working on other scripts but your still not sending emails...

**Comment by phpchess** [comment]
have you tried no settings at all? phpmailer should pick up the defaults.
phpmailer is distributed in unaltered form so you can find it in the includes folder. 
try it directly inside the folder to test it. scripts are there for testing.

let me know how you get on

Christian

**Comment by AlphabetoPT** [comment]
Cant get it to work!
i tried i really do!

If i create an Ftp user to a web accessible directory and a phpmyadmin user with the same credencials would you set it up for me?
I would appreciate.
Thanks

**Comment by phpchess** [comment]
Sure phpchess at gmail.com
